repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-added-large-files


-   repo: https://github.com/returntocorp/semgrep
    rev: 'v0.96.0'
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ['--config', './semgrep_rules.yaml', '--error']
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.267'
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "(settings|webhook_settings|migrations)"
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: [-L, 'ist,unter,oder,sie']  # codespell spreche kein deutsch
        exclude: json
