version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
        - "5002:5000"
    depends_on:
      - database
    command: flask run --host=0.0.0.0 --port=5000 --reload

  database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
